@startuml

class EventCategory{
    id
    name : String
    votable : Boolean
    + get(id)
    + getAll()
    + post(id)
    + put()
    + delete(id)
}

class Event{
    id
    title : String
    eventInfo : EventInfo
    image : EventPicture
    startDateTime : DateTime
    endDateTime : DateTime
    eventLocation : EventLocation
    category : EventCategory
        + getAll()
        + post(id)
        + put()
        + delete(id)
}

class EventInfo{
    id
    infoText : String
    pictures : List<Picture>
    + get(id)
    + post(id)
    - put()
    - delete(id)
}

class Picture{
    id
    title : String
    path : String
    - put()
    - delete(path)
}

class EventLocation{
    id
    name : String
    + get(id)
    + getAll()
    + put()
    + delete(id)
}

class Vote{
    votingCandidateID
    votingListId
    userId
    + put()
}

class VotingCandidate{
    eventID
    votingListId
    + getByVotingListId(votingListId)
}

class VotingList{
    id
    title : String
    eventCategoryId
    + getAll() ?
    + getByEventCategory(eventCategoryId)
    + post(id) ?
    + put() ?
    + delete(id)
}

note "datatype of DateTime must be discussed" as N3
note "datatype of ids must be discussed" as N2
note "coming fom frontend" as N1

Event::image -- Picture
Event::eventLocation -- EventLocation
Event::category -- EventCategory
Event::eventInfo -- EventInfo
EventInfo::pictures -- Picture
Vote::votingCandidateID -- VotingCandidate::id
Vote::userId -- N1
VotingCandidate::eventID -- Event::id
VotingCandidate::votingListId -- VotingList::id
VotingList::eventCategoryId -- EventCategory::id
VotingList::votingListId -- Vote:votingListId





@enduml