quarkus:
  resteasy:
    path: /api

  datasource:
    db-kind: postgresql

  liquibase:
    migrate-at-start: true

#  TODO: oidc
  container-image:
    builder: jib
    name: irfc-backend
#    group: irfc
    build: true
    push: false
#    regestry: registry.github.com

#  kubernetes-config:
#    enabled: false
#    namespace: ${KUBERNETES_NAMESPACE:default}
#
#  kubernetes-client:
#    namespace: ${KUBERNETES_NAMESPACE:default}

"%prod":
  container-image:
    build: true
    push: true
  liquibase:
    contexts: prod

"%dev":
  quarkus:
    datasource:
      username: test
      password: test
      devservices:
        port: 5432

    liquibase:
      contexts: dev
      migrate-at-start: true
