quarkus:
  resteasy:
    path: /api

  datasource:
    db-kind: postgresql

  liquibase:
    migrate-at-start: true

#  TODO: oidc

  container-image:
    builder: jib
    registry: ghcr.io
    name: irfc-backend
    group: fh-joanneum-iron-road-for-children
    build: true
    push: true

#  kubernetes-config:
#    enabled: false
#    namespace: ${KUBERNETES_NAMESPACE:default}
#
#  kubernetes-client:
#    namespace: ${KUBERNETES_NAMESPACE:default}

"%prod":
  quarkus:
#    container-image:
#      build: true
#      push: true
    liquibase:
      contexts: prod

"%dev":
  quarkus:
    datasource:
      username: test
      password: test
      devservices:
        port: 5432

    liquibase:
      contexts: dev
      migrate-at-start: true

#    container-image:
#      build: false
#      push: false
