quarkus:
  resteasy:
    path: /api

  datasource:
    db-kind: postgresql

  liquibase:
    migrate-at-start: true

  oidc:
    client-id: backend-api
    auth-server-url: https://irfc.eu.auth0.com/
    token:
      audience: https://backend.irfc.fh-joanneum.at/

  container-image:
    builder: jib
    registry: ghcr.io
    name: irfc-backend
    group: fh-joanneum-iron-road-for-children
    build: true
    push: true
    additional-tags: ["latest"]

  swagger-ui:
    always-include: true

  http:
    cors:
      ~: true
      origins: '*'
      access-control-allow-credentials: true
      exposed-headers: Access-Control-Allow-Origin
      methods: GET, POST, PUT, DELETE
      access-control-max-age: 24h

#  kubernetes-config:
#    enabled: false
#    namespace: ${KUBERNETES_NAMESPACE:default}
#
#  kubernetes-client:
#    namespace: ${KUBERNETES_NAMESPACE:default}

"%prod":
  quarkus:
#    container-image:
#      build: true
#      push: true
    liquibase:
      contexts: prod

"%dev":
  quarkus:
    datasource:
      username: test
      password: test
      devservices:
        port: 5432

    liquibase:
      contexts: dev
      migrate-at-start: true
    hibernate-orm:
      log:
        sql: true

pictures:
  root_path: ${PICTURES_ROOT_PATH:C:/temp/pics/}
  url: ${PICTURES_URL:http:/env-var.failed}


#    container-image:
#      build: false
#      push: false
