name: Build Quarkus Container
run-name: ${{ github.actor }} builds quarkus container
on:
  push:
    branches: [ develop-#35-setup-ci-cd ]
    paths-ignore:
      - '.gitignore'
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Login to GitHub Container Registry
        run: echo "${{ secrets.GHCR_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Build with Maven
        run: mvn package